# active users constants - temporary (will move to dedicated file)
PHASE_NUM_INDEX = 0
CAMPAIGN_INDEX = 1
EXPECT_TEXT_INPUT = 2

# PHASE DICTIONARY CONSTANTS
PHASE_NAME_INDEX = 0
PROMPT_MSG_INDEX = 1

# CONFIRMATION MESSAGE CONTANTS
VALUE_INDEX = 0

INVALID_INPUT = -1


# DATE CONSTANTS
JANUARY = 1
DECEMBER = 12

DAY_ONE = 1
LAST_DAY_MONTH = 31

# PHASE_CONSTANTS
NAME = 0
START_DATE = 1
END_DATE = 2
DAILY_BUDGET = 3
LOCATIONS = 4
NEG_LOCATIONS = 5
DOMAIN = 6
TARGETS = 7
MANUAL_CPC = 8
AD_TEXT = 9
