from enum import IntEnum

# active users constants
PHASE_NUM_INDEX = 0
CAMPAIGN_INDEX = 1
EXPECT_TEXT_INPUT = 2

# PHASE DICTIONARY CONSTANTS
PHASE_NAME_INDEX = 0
PROMPT_MSG_INDEX = 1

# CONFIRMATION MESSAGE CONTANTS
VALUE_INDEX = 0

# INVALID INPUT INDEX (Error Handling)
INVALID_INPUT = -1

# DATE CONSTANTS
JANUARY = 1
DECEMBER = 12

DAY_ONE = 1
LAST_DAY_MONTH = 31

# PHASE_CONSTANTS (order of configuration)
class PHASE_NUM(IntEnum):
  VIEWING_KEYWORD_CAMPAIGNS = -4
  DELETE_CAMPAIGN = -3
  VIEWING_CAMPAIGNS = -2
  INACTIVE = -1
  KEYWORD_CAMPAIGN = 0
  NAME = KEYWORD_CAMPAIGN + 1
  START_DATE = NAME + 1
  END_DATE = START_DATE + 1
  DAILY_BUDGET = END_DATE + 1
  MANUAL_CPC = DAILY_BUDGET + 1
  DOMAIN = MANUAL_CPC + 1
  TARGETS = DOMAIN + 1
  LOCATIONS = TARGETS + 1
  NEG_LOCATIONS = LOCATIONS + 1
  AD_TEXT = NEG_LOCATIONS + 1
  SUBMISSION = AD_TEXT + 1

# DATE CONVERSION CONSTANTS
MONTH = 0
DAY = 1
YEAR = 2

# DSA Webapp URL
DSA_URL = 'https://dsa-uplift-estimation-2020.uc.r.appspot.com'