# active users constants
PHASE_NUM_INDEX = 0
CAMPAIGN_INDEX = 1
EXPECT_TEXT_INPUT = 2

# PHASE DICTIONARY CONSTANTS
PHASE_NAME_INDEX = 0
PROMPT_MSG_INDEX = 1

# CONFIRMATION MESSAGE CONTANTS
VALUE_INDEX = 0

# INVALID INPUT INDEX (Error Handling)
INVALID_INPUT = -1

# DATE CONSTANTS
JANUARY = 1
DECEMBER = 12

DAY_ONE = 1
LAST_DAY_MONTH = 31

# PHASE_CONSTANTS (order of configuration)
INACTIVE = -1
NAME = 0
START_DATE = 1
END_DATE = 2
DAILY_BUDGET = 3
MANUAL_CPC = 4
DOMAIN = 5
TARGETS = 6
LOCATIONS = 7
NEG_LOCATIONS = 8
AD_TEXT = 9
SUBMISSION = 10

# DATE CONVERSION CONSTANTS
MONTH = 0
DAY = 1
YEAR = 2
