env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - google
parserOptions:
  ecmaVersion: 11
rules: 
  no-unused-vars: warn
  no-multi-spaces: off
  require-jsdoc: off
  valid-jsdoc: off

