name: Java Style Check

# Triggers the workflow on pull request events.
on: pull_request

jobs:
  JavaCheckStyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style against Google Java style guide
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: google_checks.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'JavaCheckStyle'
